version: "3.9"

services:
  products-db:
    image: postgres:15
    container_name: products-db
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: products_db
    ports:
      - "5432:5432"
    volumes:
      - products_data:/var/lib/postgresql/data

  products-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: products-api
    restart: always
    depends_on:
      - products-db
    environment:
      DB_HOST: products-db
      DB_PORT: 5432
      DB_NAME: products
      DB_USER: myuser
      DB_PASSWORD: mypassword
    ports:
      - "8081:8081"

volumes:
  products_data: